import type { NextPage } from "next";
import Head from "next/head";
import GeometricBackground from "../components/GeometricBackground/GeometricBackground";
import Navigation from "../components/Navigation/Navigation";
import AboutPage from "../components/_AboutPage/AboutPage";
import ContactPage from "../components/_ContactPage/ContactPage";
import HomePage from "../components/_HomePage/HomePage";
import ProjectsPage from "../components/_ProjectsPage/ProjectsPage";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pages-wrapper">
        <GeometricBackground />
        <Navigation />
        <HomePage />
        <AboutPage />
        <ProjectsPage />
        <ContactPage />
      </div>
    </>
  );
};

export default Home;
