import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import HomeBackgroundPolygons from "../components/homeBackgroundPolygons/homeBackgroundPolygons";
import SquarePrismName from "../components/SquarePrismName/SquarePrismName";
const Home: NextPage = () => {
  return (
    <div className={styles.homeWrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeBackgroundPolygons />
      <SquarePrismName />
    </div>
  );
};

export default Home;
